### ISSUE TITLE
Unity command line references

### ISSUE THREAD

**Issue by dtretyakov** [JetBrains/teamcity-unity-plugin#1]
The following references could be used to provide required parameters in UI:
* https://discuss.bitrise.io/t/how-to-build-a-unity-project/1317
* https://docs.unity3d.com/Manual/CommandLineArguments.html

Unity installation from command line:
https://github.com/DragonBox/u3d

Examples:
* https://github.com/zfergus/unity-examples
* [TDD blog post](https://blogs.unity3d.com/2018/11/02/testing-test-driven-development-with-the-unity-test-runner/) and [code](https://github.com/sophiaaar/tdd-pong)

**Comment by lesley29** [comment]
Closing this as it seems to be outdated
