### ISSUE TITLE
Add the option to use the -cleanedLogFile flag.

### ISSUE THREAD

**Issue by ArtOfSettling** [JetBrains/teamcity-unity-plugin#18]
The cleanedLogFile flag is not officially documented, but it allows unity to dump out a log without callstacks, which makes reading the log in TeamCity's build window much easier.

Our log files are about 6 - 30 mb depending on the build so they don't display well in TeamCity's build log window if we have a full log.

**Comment by dtretyakov** [comment]
@ArtOfSettling, thanks for letting me know about it. Now by default will be used `-cleanedLogFile` argument. To enable verbose logging (`-logFile`) could be used "Logging verbosity" runner parameter.

**Comment by ArtOfSettling** [comment]
That sounds great! Thanks for the addition.
