### ISSUE TITLE
Please add Android build support?

### ISSUE THREAD

**Issue by Temka193** [JetBrains/teamcity-unity-plugin#20]
![image](https://user-images.githubusercontent.com/11135702/51624280-840d8e80-1f4b-11e9-888c-21b15574838a.png)
I do not understand why this item is, if this is a choice of platform, then why is there no android?

**Comment by dtretyakov** [comment]
@Temka193, you're using [obsolete Unity runner](https://github.com/mindcandy/Teamcity-unity3d-build-runner-plugin). The runner for this plugin looks different:
https://plugins.jetbrains.com/plugin/11453-unity-support

If you have installed JetBrains plugin alongside with old plugin you need to select "Unity (JetBrains plugin)" runner.

There you could use specific BuildScript's method in "Execute method" parameter or specify target parameter to build android app.

**Comment by dtretyakov** [comment]
@Temka193, please let me know if it's still relevant.

**Comment by AdamFrisby** [comment]
Bumping this - this should be a relatively easy one. Would also like to request iOS as well (although that requires a separate XCode step - at least the XCode project part could be built)
