### ISSUE TITLE
Playmode tests doesn't run

### ISSUE THREAD

**Issue by anmelegov** [JetBrains/teamcity-unity-plugin#22]
To run playmode tests you need to replace "-runEditorTests" with "-runTests" according to unity reference https://docs.unity3d.com/Manual/PlaymodeTestFramework.html . Please also note that "-editorTestsResultFile" is ignored for playmode tests

**Comment by dtretyakov** [comment]
@anmelegov, thanks for reporting. Proper arguments will be used when "Test platform" is specified and it'll be available in the [next bug fix update](https://plugins.jetbrains.com/plugin/11453-unity-support).
