### ISSUE TITLE
Use logFile without file path in Unity 2019.1 on Windows

### ISSUE THREAD

**Issue by dtretyakov** [JetBrains/teamcity-unity-plugin#24]
In Unity Editor 2019.1+ it's possible to get build log in stdout with `-nographics` option:
https://issuetracker.unity3d.com/issues/command-line-logfile-with-no-parameters-outputs-to-screen-on-os-x-but-not-on-windows

**Comment by samyzain** [comment]
great post. thanks you.
http://www.winmilliongame.com
http://www.gtagame100.com
http://www.subway-game.com
http://www.zumagame100.com
