### ISSUE TITLE
Support custom Unity home paths

### ISSUE THREAD

**Issue by dtretyakov** [JetBrains/teamcity-unity-plugin#25]
Being able to force the path in the build configuration, or via an environment variable which can be adjusted on a per-config basis would be useful.

We store all our Unity installs in C:\Unity\* - it'd be nice if we could get the option to change the search directory from Program Files, et al - to there.

_Originally posted by @AdamFrisby in https://github.com/JetBrains/teamcity-unity-plugin/issues/6#issuecomment-461132407_

**Comment by dtretyakov** [comment]
@AdamFrisby, in the [latest plugin build](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityUnityPlugin_Build&guest=1) you could specify environment variable `UNITY_HINT_PATH=C:\` on your build agents to find Unity installations in C drive root folder.

> Being able to force the path in the build configuration, or via an environment variable which can be adjusted on a per-config basis would be useful.

Is not enough for you to have "Unity version" parameter in the Unity build runner?
![image](https://user-images.githubusercontent.com/1025927/52733188-68355f80-2fc2-11e9-9f5a-e796db213612.png)

**Comment by AdamFrisby** [comment]
It generally is enough yes. The only case I can see where it wouldn't be, would be us using patch versions simultaneously (often they're buggy/unstable, but fix a bug we need for test builds)

**Comment by lesley29** [comment]
Closing as in the recent versions of the plugin, it's possible to set a custom path to Unity to be used in the build by selecting "manual" detection mode. Feel free to reopen if it doesn't work in your scenarios
<img width="742" alt="Screenshot 2024-06-26 at 16 55 11" src="https://github.com/JetBrains/teamcity-unity-plugin/assets/39089602/56f8ba53-4f5d-4df6-8f5e-72d0c6725a71">
