### ISSUE TITLE
Potential issue with Runner and multiple unity steps on one build configuration.

### ISSUE THREAD

**Issue by WellFiredDevelopment** [JetBrains/teamcity-unity-plugin#26]
I wonder if with the following code..

![screenshot 2019-02-23 at 15 33 59](https://user-images.githubusercontent.com/33579768/53282829-8fd5b600-3780-11e9-811a-9d6fd849d31b.png)

You could run into issues with multiple unity steps in one build configuration.

I.e. 

Step 1. Import
Step 2. Build
Step 3. Test

Maybe it's possible to have the step number here, such as...

"-${build.buildId}.${build.stepId}"

I'm not sure if this would be possible but it seems like it might be a small change for additional features.

I tend to run multiple unity steps in one configuration and then artifact each of their logs seperately.

Edit : Sorry, I was supposed to make this a question / suggestion

**Comment by dtretyakov** [comment]
@WellFiredDevelopment, actually before each build agent temp directory is cleaned and `File.createTempFile` method always appends unique numeric value between specified prefix and suffix arguments, so they would not clash if you have multiple Unity build step, e.g:
```
 Directory of C:\buildAgent\temp\buildTmp

02/25/2019  12:15 PM    <DIR>          .
02/25/2019  12:15 PM    <DIR>          ..
02/25/2019  12:13 PM    <DIR>          NVIDIA Corporation
02/25/2019  12:15 PM               718 unityBuildLog-129554086583396480.txt
02/25/2019  12:14 PM               718 unityBuildLog-518438696835135993.txt
02/25/2019  12:14 PM                 0 unityTestResults-3637851416253034745.xml
02/25/2019  12:13 PM                 0 unityTestResults-4386295299773836064.xml
```

**Comment by WellFiredDevelopment** [comment]
Perfect! Thank you so much for your response.
