### ISSUE TITLE
Unity installation detection on custom drive

### ISSUE THREAD

**Issue by btsslawa** [JetBrains/teamcity-unity-plugin#27]
Hey there,
I spent the whole day trying to setup Teamcity with Unity with the Unity Plugin for teamcity in order to create a build pipeline - and for the love of god I couldn't set it up. Whatever parameters I'm trying to set, my build agent (my very own machine) is always incompatible. I don't even get to the build part, since the agent is incompatible with this reason:

Unmet requirements:
Exists=>unity\.path\.2018\.3\.6f1.* exists

Now apparently the main problem is that the path of the specific Unity installation cant be found.
I use Unity Hub and Unity Hub and all the Unity versions are installed on a different harddrive (on drive D:), and Unity Hub installs all my Unity Versions to this folder:
D:\Programme\Unity 

So for example Unity 2018.3.6f1 is installed in:
D:\Programme\Unity\2018.3.6f1

Now when I created the Build Step and chose Unity as the Runner Type, I opened the advanced settings, set all the necessary things and set the Unity version like this: 2018.3.6f1

Saving that Build Step and hitting "Run" leads to the unmet requirement.
First thing: Is there any chance to debug? Or at least to get any logs? Because you know "Exists=>unity\.path\.2018\.3\.6f1.* exists" doesn't say anything about the problem, it seems it doesn't find the path, but why not, what exactly is wrong, how does the processed path actually look like?

Now looking at the Configuration of the readme.md we also tried to create an Environment Variable in the Parameters of the Build Configuration called UNITY_HINT_PATH to hint at the Unity Hub but that didn't work and we also tried the same with UNITY_HOME like this:
Name: env.UNITY_HOME    Value: D:/Programme/Unity/2018.3.6f1 

I tried it to with other Unity versions and their respective paths, but it nerver worked.

What's the exact issue? What did I do wrong?

**Comment by dtretyakov** [comment]
@btsslawa, sorry if it was not clear from the plugin description, but in case of custom unity installation folder you need to specify `UNITY_HOME` environment variable on your build agent machine, not in the build configuration parameters.

Then you need to restart TeamCity build agent and check on the agent configuration parameters page that it has defined parameter starting with `unity.path`.

Also in the `teamcity-agent.log` file you could find mentions of found unity installations.

And thanks for describing use case with Unity installation on custom drive, we'll support automatic detection of it in further versions.

**Comment by dtretyakov** [comment]
Relates to https://github.com/JetBrains/resharper-unity/issues/850

**Comment by dtretyakov** [comment]
@btsslawa, you could update your plugin to the latest build where your use case is supported without tricks with hint paths: https://plugins.jetbrains.com/plugin/11453-unity-support

Please let me know if it solves the problem.

**Comment by btsslawa** [comment]
Thanks for the update! Highly appreciated. Installed the plugin and restarted TeamCity, run the build but I still get the very same error.
Here's a screenshot of my buildstep.
![buildstep](https://user-images.githubusercontent.com/38842677/54026889-c4456b00-419f-11e9-89e3-fe5ec323b4e6.PNG)
And here's a screenshot of my Unity Installations folder with all the installed versions, Unity Hub was also installed there and points to this directory to install the respective Unity versions, which is
"D:\Programme\Unity" in my case:
![unityinstallations](https://user-images.githubusercontent.com/38842677/54026921-df17df80-419f-11e9-83a2-049dab5202e4.PNG)

Did I miss something with the plugin update?

**Comment by dtretyakov** [comment]
@btsslawa, could you please share the list of parameters prefixed by "unity.path" from the %agent% ->Agent Parameters -> Configuration parameters page?

Also please remove the `f1` prefix in the "Unity version" build step parameters, since on the Unity plugin reports normalized version parameters.

**Comment by btsslawa** [comment]
I removed the f1 prefix, thanks for the hint!

I looked at the Agent Parameter Page and it was empty:
![configparamsempty](https://user-images.githubusercontent.com/38842677/54028763-6bc59c00-41a6-11e9-9ff9-3c32c19c0eaf.PNG)

I added a parameter like this:
![configparams](https://user-images.githubusercontent.com/38842677/54028774-72ecaa00-41a6-11e9-994c-7b41349717a7.PNG)


Sorry to annoy you with this, never worked with CI tools before...

**Comment by dtretyakov** [comment]
@btsslawa,
> %agent% ->Agent Parameters -> Configuration parameters page?

It looks like that:
![image](https://user-images.githubusercontent.com/1025927/54030014-9ca7d000-41aa-11e9-8356-7c0369ea601a.png)

There find parameters prefixed by "unity.path" and ensure that all Unity Editor versions are mentioned there:
![image](https://user-images.githubusercontent.com/1025927/54030121-e1336b80-41aa-11e9-8c07-8f570fb4808c.png)

If you could not find them in the list but you see them in the "Unity Hub" in Installs -> On my machine section please share the `editors.json` and the `secondaryInstallPath.json` from the `%AppData%\UnityHub\` directory.

Thanks.

**Comment by btsslawa** [comment]
Ah, that list. No, there are no unity.path configuration parameters in that list available.

editors.json looks like this:

> {"5.4.5p3":{"version":"5.4.5p3","location":["D:\\Programme\\Unity\\5.4.5p3\\Unity\\Editor\\Unity.exe"],"manual":true},"2018.3.6f1":{"version":"2018.3.6f1","location":["D:\\Programme\\Unity\\Hub\\Editor\\2018.3.6f1\\Editor\\Unity.exe"],"manual":true}}

And secondaryInstallPath.json looks like this
> "D:\\Programme\\Unity"

**Comment by dtretyakov** [comment]
@btsslawa, thanks for details. It looks like Unity Hub does not properly escape special characters in paths, e.g.:

```json
{
	"5.4.5p3": {
		"version": "5.4.5p3",
		"location": ["D:\Programme\Unity\5.4.5p3\Unity\Editor\Unity.exe"],
		"manual": true
	},
	"2018.3.6f1": {
		"version": "2018.3.6f1",
		"location": ["D:\Programme\Unity\Hub\Editor\2018.3.6f1\Editor\Unity.exe"],
		"manual": true
	}
}
```
is not valid JSON and should look like that:
```json
{
	"5.4.5p3": {
		"version": "5.4.5p3",
		"location": ["D:\\Programme\\Unity\\5.4.5p3\\Unity\\Editor\\Unity.exe"],
		"manual": true
	},
	"2018.3.6f1": {
		"version": "2018.3.6f1",
		"location": ["D:\\Programme\\Unity\\Hub\\Editor\\2018.3.6f1\\Editor\\Unity.exe"],
		"manual": true
	}
}
```

Could you please report your Unity Hub version and update `editors.json` file content by correct value?

Then please open the `%buildAgent%/config/teamcity-agent-log4j.xml` file, remove comments before and after `<priority value="DEBUG"/>` line in the following section and restart TeamCity build agent:
```xml
<category name="jetbrains.buildServer">
    <!--DELETE THIS LINE FOR ENABLING DEBUG LOGGING--> <!--
    <priority value="DEBUG"/>
--> <!--DELETE THIS LINE FOR ENABLING DEBUG LOGGING-->
    <appender-ref ref="ROLL"/>
  </category>
```
After that please share the `teamcity-agent.log` file for investigation. Thanks.

**Comment by btsslawa** [comment]
Oh, there seemed to be a problem with copy&pasting into this comment section, the files do have the escaped slashes:
![jsonfile](https://user-images.githubusercontent.com/38842677/54034993-97ea1880-41b8-11e9-85e2-c7948758d985.PNG)

My Unity Hub version is the latest one, updated it today: 1.6.0
Here's the attached log file:
[teamcity-agent.log](https://github.com/JetBrains/teamcity-unity-plugin/files/2946204/teamcity-agent.log)

**Comment by dtretyakov** [comment]
@btsslawa, thanks for the logs.

Do you use the same user account to run TeamCity build agent and for log in to this machine? It maybe the case that you're running TeamCity build agent under `Local System` user account which does not have access to Unity Hub configs. To check it open Services -> "TeamCity Build Agent", specify user account credentials and restart build agent:

![image](https://user-images.githubusercontent.com/1025927/54037545-b3f0b880-41be-11e9-80b3-f4812f1d7918.png)

If it helps you could restore logging section in the `teamcity-agent-log4j.xml` file.

**Comment by btsslawa** [comment]
I only have one user on my PC. Looking at the "My Settings & Tools"-section of TeamCity the username is different from the user name of my OS/machine.

I looked at the Build Agent Property as you suggested and it was set to "Local System Account", the "Allow Service to interact with Desktop" was also set.
I changed that to the user name I use for my PC/machine, restarted TeamCity and tried to run the build again => same issue.

**Comment by dtretyakov** [comment]
@btsslawa, could you please check that any "unity.path" parameters has been appeared on the 
 agent "Configuration parameters" page after build agent restart?

If you could not see them please share the fresh `teamcity-agent.log` file for investigation?

**Comment by btsslawa** [comment]
I got it working! I noticed that for some reason the build agent was disconnected, apparently after I changed the property in the Service. Started the service again manually and the build kicked off immediately. Now I see all the unity.path variables with the correct paths in the configuration parameter list. Awesome :)

Highly appreciate all the help @dtretyakov

**Comment by dtretyakov** [comment]
@btsslawa, great. Will reflect notes about user account in readme file.
