### ISSUE TITLE
Allow use of a configuration parameter for the Unity Version

### ISSUE THREAD

**Issue by fklingler** [JetBrains/teamcity-unity-plugin#28]
Hello!

I'd want to use a teamcity Configuration Parameter to configure the Unity Version, so my team can easily swap the version used when running a build (notably using the "custom run" button).

Unfortunately, this doesn't seem to work, as my agent is shown as incompatible:
![image](https://user-images.githubusercontent.com/282439/54220891-aacf5680-44f2-11e9-895b-38a86d85d8f7.png)

It doesn't seem that the configuration parameter is interpreted before the unity version is tested for the agents

**Comment by dtretyakov** [comment]
@fklingler, at the moment TeamCity does not support parameters resolution in agent requirements: https://youtrack.jetbrains.com/issue/TW-5661

You could vote/watch for the mentioned issue.

**Comment by fklingler** [comment]
Thanks, I will do that!

FYI, this enhancement you suggested https://github.com/JetBrains/teamcity-unity-plugin/issues/19 would also allow me to do what I want!

**Comment by ArtOfSettling** [comment]
Is there anyway we can build the runner to work around this issue? I'm also facing it and for now i'm just disabling the requirement check on my fork and using that rather than the official plugin. (We rely heavily on metarunners with parameters)

**Comment by AaronZurawski** [comment]
Without this feature, updating several build configs that are all based on a handful of different templates becomes monotonous and error-prone. With a parameterized field, its a simple, easily-enforceable change.

I've voted for the related TeamCity feature request as well.

**Comment by tallior** [comment]
@dtretyakov i realize TC doesn't support parameter resolution in agent requirements, but is there a way to overcome this, for example, by re-working how this mechanism works (e.g: don't use agent requirements) ?

This is a really basic requirement (setting different Unity versions) and the fact it's not working makes it very difficult to work with this plugin.

**Comment by dtretyakov** [comment]
@NikolayPianikov maybe we could somehow overcome this issue?

**Comment by AaronZurawski** [comment]
I have submitted a PR #54 that adds support for TeamCity to be managed as a TeamCity agent tool. This may provide a viable alternative to solve this issue.

**Comment by lesley29** [comment]
It seems like a bit irrelevant issue was mentioned here earlier. As I can see, TC does support property resolution in agent requirements since 2020.2 EAP3.
Relevant links:

- https://github.com/JetBrains/teamcity-unity-plugin/issues/51
- https://youtrack.jetbrains.com/issue/TW-19877/Support-property-resolution-references-to-agent-parameters-in-agent-requirements

Please feel free to reopen this issue if you are still running into the described problem.
