### ISSUE TITLE
Support simultaneous versions of Unity minor versions

### ISSUE THREAD

**Issue by pichardjerome** [JetBrains/teamcity-unity-plugin#30]
Our Teamcity build agent doen't use the correct version of Unity. We need to build our project with Unity2018.2.13f1, but our build agent always use Unity2018.2.16f1 because this version is used for another game, which is built on the same agent...

Could you please add ability to specify minor version or full path of Unity Editor ?
Thanks

![TeamcityUnityRunner](https://user-images.githubusercontent.com/10053070/54747298-c7445080-4bce-11e9-8076-2283b18d123d.png)

**Comment by ArtOfSettling** [comment]
I think this is actually caused by a bug in the detection algorithm. I have the same issue, i'll put a pull request in shortly.

**Comment by ArtOfSettling** [comment]
For reference...

https://github.com/JetBrains/teamcity-unity-plugin/pull/31 <--- This pull request enables what @pichardjerome is asking for.
