### ISSUE TITLE
Unity Tool install isn't triggered and build is blocked by path variable usage

### ISSUE THREAD

**Issue by AaronZurawski** [JetBrains/teamcity-unity-plugin#35]
If you install Unity as a TeamCity tool using the instructions provided by JetBrains and linked in the Readme, the build that references that new version will be blocked indefinitely as the tool is not triggered to install by the build and the `unity.path.<version>` Configuration Parameter causes the build to not find compatible agents as the Tool not only needs to be installed, but also needs to trigger the Unity Runner Plugin to re-search for Unity installations to populate this field.

So I see 2 related but distinct issues here:
1. Runner doesn't inform TeamCity to install the Tool
2. Once tool is installed, a restart of the agent is required as the Unity Runner doesn't update its path variables as a response to a tool install

My repro case:
1. Already have a licensed Unity install on the Agent
2. Create a new tool for a new Unity version (2018.4.6) using the documentation here: [Installing Agent Tools](https://www.jetbrains.com/help/teamcity/installing-agent-tools.html) and here: [Plugins Packaging](https://plugins.jetbrains.com/docs/teamcity/plugins-packaging.html?_ga=2.54199912.112789028.1565708271-1432284306.1556119626#Tools)
3. Install new Tool using TeamCity Administration page
4. Create a new build configuration with the Unity Runner and set the version to this new tool

**Expected**: Build runs, triggering tool install on agent that does not yet have that tool
**Actual**: Build is blocked indefinitely as `unity.path.2018.4.6` is not defined and the build will not run to install the tool.

**Comment by ArchyInf** [comment]
Same issue. It should be possible to define a %teamcity.tool.XXX% as Unity version which simply installs the tool on the agent and passes it's path as the unity executable without introducing any build requirements.

**Comment by ArchyInf** [comment]
Added a pull request:
https://github.com/JetBrains/teamcity-unity-plugin/pull/39

This allows calling Unity binary from an agent tool without dependencies by supplying an exeplicit executable, eg %teamcity.tool.unity_master%\\Editor\\Unity.exe

**Comment by ArchyInf** [comment]
Cleaned up PR; New to this, new one #43
