### ISSUE TITLE
Build step only runs Edit mode or Play mode

### ISSUE THREAD

**Issue by Bullrich** [JetBrains/teamcity-unity-plugin#38]
The `<Default>` option in Test Platform runs only the *EditMode* tests.

It would be nice to have an option that runs both, Edit and Play mode tests, instead of needing one Build Step for each kind of tests.

Could this be achievable?

**Comment by NikolayPianikov** [comment]
@Bullrich did you suppose to have different sets of _Test categories_ and _Test names_ for each mode?

**Comment by Bullrich** [comment]
Issue is currently not required anymore. Closing issue.
