### ISSUE TITLE
Incorrect Unity discovery on Linux

### ISSUE THREAD

**Issue by citizenmatt** [JetBrains/teamcity-unity-plugin#47]
The current Linux discovery tries to look at `$UNITY_ROOT/Editor/Data/PackageManager/Unity/PackageManager` to find the version, but this path doesn't exist, and discovery fails. AFAICT, there is no reliable way to get the current Unity version, other than parsing the name of the containing folder.

**Comment by reapazor** [comment]
I'm with him, use the path of the root to get it - /home/user/Unity/Hub/Editor/version/

**Comment by hikk** [comment]
the same
