### ISSUE TITLE
Is this project mantained?

### ISSUE THREAD

**Issue by Bullrich** [JetBrains/teamcity-unity-plugin#50]
From what I have seen in the history the project has **9 commits this year** (and two of them were just [copyright](https://github.com/JetBrains/teamcity-unity-plugin/commit/94723364c38788bfafa84eee1178414cd85d159b) and [vendor](https://github.com/JetBrains/teamcity-unity-plugin/commit/2ec6acc09b38421cef6bdd8ba9d19e173ce0ad1c) stuff), the latest commit has been on March, and before that, the closest commit was in April 2019 (*8 months of inactivity* in between), 4 open PRs that aren't active, and 21 (now 22) issues still waiting for a resolution.

Also, the latest release in the [Plugin site](https://plugins.jetbrains.com/plugin/11453-unity-support) (with the download link) points to `SNAPSHOT-20200127164629` released in Jan 28, 2020, which means that all the latest fixes aren't available (unless, of course, that you build the whole plugin by yourself), it was only released again because of the copyright stuff. Following this pattern, we can expect that the next update will only be available in 2021 when @orybak upgrades the copyright year.

I've been struggling with problems and been trying to find solutions, report problems or even fix them, but after seeing the current status, it demotivates me and my team from staying with Teamcity. It feels like this plugin was made because it *had* to be made and after that it was just let alone.

Can we expect the contributors to participate more in the repository and help the developers?

**Comment by dmitry-treskunov** [comment]
Hi, you are right, we didn't make a lot of commits to the plugin recently, but we hope to start maintaining it better. Sorry for the inconvenience.

**Comment by Bullrich** [comment]
Thanks for your response! I look forward to have more updates then 😄

**Comment by lesley29** [comment]
Closing this one as it seems to be answered :) 
The plugin is currently back under development and in the stage of housekeeping.

**Comment by Bullrich** [comment]
I'm very happy to hear this.

Amazing that this project is again under active maintenance.

Great job guys!
