### ISSUE TITLE
Unity Version field doesn't allow the use of Teamcity parameters

### ISSUE THREAD

**Issue by Bullrich** [JetBrains/teamcity-unity-plugin#51]
When using a parameter or environment variable for the field `Unity Version`, the agent evaluates it as a literal string instead of a Teamcity variable.

Setting all the unity steps in a single parameter would reduce the overhead of manually configuring them individually.

### Steps to reproduce

Set a `configuration parameter` or a `environment variable` with the unity version:
![image](https://user-images.githubusercontent.com/8524599/92391731-76574d80-f11d-11ea-85b4-e66982c3a5a1.png)

Use the parameter in the `Unity Version` field:
![image](https://user-images.githubusercontent.com/8524599/92391920-c2a28d80-f11d-11ea-9846-68a9849f4723.png)

Look at the Compatible agents (I set one step to use `%env.UNITY_VERSION%` and the other to use `%UNITY_VERSION%`:
![image](https://user-images.githubusercontent.com/8524599/92392009-e9f95a80-f11d-11ea-982b-2a0afa7776e3.png)

### Expected result:
Requirement should say: 
`Exists=>unity\.path\.2019\.4\.7* exists`

**Comment by NikolayPianikov** [comment]
Depends on https://youtrack.jetbrains.com/issue/TW-68102
Will be available in TeamCity 2020.2 EAP3

**Comment by Bullrich** [comment]
Thanks a lot for fixing this issue!
