### ISSUE TITLE
Plugin Does Not Build

### ISSUE THREAD

**Issue by MrBinaryCats** [JetBrains/teamcity-unity-plugin#65]
If you try to clone this repo and build the plugin using Gradle, There will be several errors you encounter.

**ISSUE #1**

- Using JDK version 16, this error is produced:  java.lang.reflect.InaccessibleObjectException: Unable to make protected `java.lang.Package[] java.lang.ClassLoader.getPackages() accessible: module java.base does not "opens java.lang" to unnamed module`

**SOLUTION**

- Use JDK 11
- Please indicate this in the readme

**ISSUE #2**

- The Gradle Version is out of date

SOLUTION

- in `\gradle\wrapper\gradle-wrapper.properties` change `distributionUrl=https\://services.gradle.org/distributions/gradle-4.9-bin.zip` to `distributionUrl=https\://services.gradle.org/distributions/gradle-7.2-bin.zip`

**ISSUE #3**
- Out of date dependancies (resulting in 403 errors)

SOLUTION

- in `\plugin-unity-agent\build.gradle`, change `compile "org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.10.0"`  to `compile "org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.14.0"`

-  in **all** `build.gradle` files, change `id 'com.github.rodm.teamcity-agent' version "1.1.1"` to `id 'com.github.rodm.teamcity-agent' version "1.4"`

--
Also in `\build.gradle`:

-  remove the line `maven { url "https://kotlin.bintray.com/kotlinx }` 
- update `sourceCompatiblity` from `1.6` to `1.7`
- update  `targetCompatiblity` from `1.6` to `1.7`

**Comment by lesley29** [comment]
Hey @MrBinaryCats !

Thanks for highlighting these problems and sorry for the long delay in replying. The plugin is currently back under development and actively maintained. We've recently fixed all of these issues, so I'm closing this one.
