### ISSUE TITLE
Highlight problems in build log

### ISSUE THREAD

**Issue by dtretyakov** [JetBrains/teamcity-unity-plugin#7]
Currently build log is displayed as is, but we could highlight warnings in it.

**Comment by ArtOfSettling** [comment]
This would be very valuable, the previous *deprecated* plugin had this functionality and it's nice to be presented with an at a glance overview on the build overview page.

**Comment by dtretyakov** [comment]
In the [recent plugin builds](https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityUnityPlugin_Build&guest=1) was added support of structured build log entries.
