### ISSUE TITLE
More platforms

### ISSUE THREAD

**Issue by BinaryJared** [JetBrains/teamcity-unity-plugin#73]
We'd like to build on all platforms Unity supports (Xbox, PS, Switch etc.), but the config only shows Windows Mac and Linux. Any way to add these?

**Comment by Autofire** [comment]
I have this same question. According to [Unity's docs](https://docs.unity3d.com/Manual/EditorCommandLineArguments.html), there are ways to specify particular platforms:
![image](https://user-images.githubusercontent.com/7464159/162586948-2b21d37f-4b44-42c5-9fca-53ac360d46b3.png)

However, when doing this in the command line args section (with WebGL anyway), it screws up the build agent and then it can no longer do any builds. I haven't tried any others (Android and iOS being the ones I'm interested in the most), but I imagine they'd work the same way.

![image](https://user-images.githubusercontent.com/7464159/162587111-ec638334-c400-4734-9b6a-a517037c36a1.png)

I'm guessing there might be a way, but the plugin docs don't specify.

**Comment by Autofire** [comment]
So what I hadn't noticed was that this exists:
![image](https://user-images.githubusercontent.com/7464159/162587716-cf742dfb-fbb5-41ad-a8f1-b4ecfe977452.png)

However, I'm still running into the same issue. I'm not sure if it's something that's off with my project or the configuration. (I should say that it's a very bare-bones project, [this one](https://github.com/Autofire/CyclesJamProject).

I have more complicated things I'd like to automate, but I'm starting simple atm.
