### ISSUE TITLE
Is this project abandoned by JB?

### ISSUE THREAD

**Issue by DallasP9124** [JetBrains/teamcity-unity-plugin#75]
There are many unanswered and unresolved issues that are quite relevant to today that were created a year ago or longer. It sure seems that JB is no longer maintaining nor cares to.

**Comment by dmitry-treskunov** [comment]
Hi, thank you for your comment.  This plugin is not abandoned by JetBrains, but, indeed, we have not put enough resources into supporting it, though we are going to change it in the nearest future and start maintaining and developing it actively since we see it's widely used by TeamCity customers
