### ISSUE TITLE
Is there a way to parameterize unity version if using the Tool installer?

### ISSUE THREAD

**Issue by danbudworthmead** [JetBrains/teamcity-unity-plugin#85]
Basically, we're testing out upgrading our unity version. We install unity with the teamcity tool config (the zip files).

Currently, I have to edit the config, change the unity version in the drop-down, run the build, then re-change that in the build config.

Is there a way to parameterize this so I could specify that unity version? Because currently if I parameterize it it won't pull it from the TeamCity tools zips, it looks for it installed on the machine.

**Comment by lesley29** [comment]
Hi @danbudworthmead,

Unfortunately, it's impossible to parameterize used tool version on the build step via the UI using parameter reference mechanism, other than selecting it via a dropdown. 

However, you could try using Kotlin DSL. If you click on "View as code" while on a runner configuration page, you can see that this configuration transforms into:
```
param("unityRoot", "%teamcity.tool.Unity-{some_version}%")
```

Is that what you are trying to achieve? 
Please let me know if this helps
