### ISSUE TITLE
Feature Request: Activation / Deactivation for any build step

### ISSUE THREAD

**Issue by nefelim4ag** [JetBrains/teamcity-unity-plugin#90]
We using Nuke for managing Unity builds, and run something like:
Script step -> build.cmd
PowerShell step -> build.ps1

Current behaviour:
- Activation/Deactivation works only for Unity step

Expected behaviour:
- Activation/Deactivation works for any build step in build configuration

With the enabled build feature for license activation, I expect Teamcity to run it on job start and end with the job.
IIRC, this is how docker login works, it just applied to every step.

Thanks!

**Comment by lesley29** [comment]
Hey @nefelim4ag!
Thanks, that definitely makes sense. You can keep track of the progress on this issue here [TW-85266](https://youtrack.jetbrains.com/issue/TW-85266/Unity-Plugin-Allow-acquiring-a-license-before-a-build-and-returning-it-afterward)

**Comment by lesley29** [comment]
Hey @nefelim4ag,

Just wanted to let you know that this feature is now available in version [1.3.0](https://plugins.jetbrains.com/plugin/11453-unity-support/versions/stable/555168). Sorry it took so long, and thanks a ton for your patience.

If you have any feedback regarding this feature or anything else, feel free to reach out.

Cheers!

**Comment by nefelim4ag** [comment]
Tested - works as expected (acquired a license on build configuration start and return afterward)
Awesome, thanks!
